apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twitter-stream
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/servian-task/pubsub-bq-pipe:v22
        env:
        - name: GCP_PROJECT
          value: servian-task
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub     
        - name: PUBSUB_TOPIC
          value: projects/servian-task/topics/hashtag-london-topic
        - name: CONSUMERKEY
          value: lbRF9YBBJvAaDPrT1PbyjIVKD
        - name: CONSUMERSECRET
          value: OL0Gg0XrDtMdHcwvyocPw7ZwvZJvlhZcMWAVi28vWiUOjejWP3
        - name: ACCESSTOKEN
          value: 1319427930439749633-MLh2G2POhQbcCIEHXMHmRcVQxrMizR
        - name: ACCESSTOKENSEC
          value: bPb6zZAN7zICHbAhwbq23Ju24igdsf0ALOBTstE1Qfr8C
        - name: TWSTREAMMODE
          value: filter
